# Generated by Django 5.2.5 on 2026-02-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='garage_size',
            field=models.CharField(max_length=50),
        ),
    ]
