# Generated by Django 5.2.5 on 2026-02-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_property_garage_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='garage',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
