# Generated by Django 5.2.5 on 2026-02-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_property_garage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='garage_size',
        ),
    ]
