# Generated by Django 5.2.5 on 2026-02-10 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_property_garage_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertylocation',
            options={'permissions': [('view_products', 'View Propertys(Menu)'), ('add_property', 'Add Property'), ('edit_property', 'Edit Property'), ('delete_property', 'Delete_Property')]},
        ),
    ]
