# Generated by Django 5.2.5 on 2026-02-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_propertylocation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertylocation',
            options={'permissions': [('view_property', 'View Propertys(Menu)'), ('add_property', 'Add Property'), ('change_property', 'Edit Property'), ('delete_property', 'Delete_Property')]},
        ),
    ]
