# Generated by Django 5.2.5 on 2026-01-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_parent_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='dash/assets/images/icons/user_img.png', null=True, upload_to='profile_images/'),
        ),
    ]
