# Generated by Django 5.2.5 on 2026-01-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/user_img.png', null=True, upload_to='profile_images/'),
        ),
    ]
