# Generated by Django 5.2.5 on 2026-02-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_dashboard', 'Permisison for Dashboard')]},
        ),
    ]
