# Generated by Django 5.2.5 on 2026-02-10 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_dashboard', 'Permisison for Dashboard'), ('view_create_associate', 'Permission for create_agent')]},
        ),
    ]
