# Generated by Django 5.2.5 on 2026-02-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_payments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
