# Generated by Django 5.2.5 on 2026-01-12 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.AddField(
            model_name='lead',
            name='agent_note',
            field=models.TextField(blank=True, help_text='Agent call response / remarks'),
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up_at',
            field=models.DateTimeField(blank=True, help_text='Next follow-up date & time', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
