# Generated by Django 5.2.5 on 2026-01-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_assigned_at_lead_email_lead_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'permissions': [('view_leads', 'Can view leads'), ('add_leads', 'Can add leads'), ('edit_leads', 'Can edit leads'), ('delete_leads', 'Can delete leads')]},
        ),
    ]
