# Generated by Django 5.2.5 on 2026-01-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={},
        ),
    ]
