# Generated by Django 5.2.5 on 2026-01-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'permissions': [('can_update_lead', 'can update lead'), ('can_delete_lead', 'can delete lead'), ('can_book_lead', 'can book lead')]},
        ),
    ]
