# Generated by Django 5.2.5 on 2026-01-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='client_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='interest_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_action',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='objections',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='property_type',
            field=models.CharField(blank=True, choices=[('plot', 'Plot'), ('flat', 'Flat'), ('villa', 'Villa'), ('commercial', 'Commercial')], max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='purchase_timeline',
            field=models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('1-3', '1–3 Months'), ('3-6', '3–6 Months'), ('enquiry', 'Just Enquiry')], max_length=20),
        ),
    ]
