# Generated by Django 5.2.8 on 2026-01-28 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_assigned_associate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('closed', 'Closed')], max_length=20)),
                ('property_type', models.CharField(blank=True, choices=[('plot', 'Plot'), ('flat', 'Flat'), ('villa', 'Villa'), ('commercial', 'Commercial')], max_length=20)),
                ('preferred_location', models.CharField(blank=True, max_length=100)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_timeline', models.CharField(blank=True, choices=[('immediate', 'Immediate'), ('1-3', '1–3 Months'), ('3-6', '3–6 Months'), ('enquiry', 'Just Enquiry')], max_length=20)),
                ('interest_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('next_action', models.CharField(blank=True, max_length=255)),
                ('client_response', models.TextField(blank=True)),
                ('objections', models.TextField(blank=True)),
                ('agent_note', models.TextField(blank=True)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='leads.lead')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead History',
                'verbose_name_plural': 'Lead Histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', '-created_at'], name='leads_leadh_lead_id_211934_idx')],
            },
        ),
    ]
