# Generated by Django 5.2.5 on 2026-02-04 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_lead_status_alter_leadhistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
