# Generated by Django 5.2.5 on 2026-02-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_alter_lead_assigned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
