# Generated by Django 5.2.5 on 2026-02-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_alter_lead_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'permissions': [('view_contacts', 'View Contacts'), ('change_contact', 'Change_Contact'), ('delete_contact', 'Delete_Contact')]},
        ),
    ]
