# Generated by Django 5.2.5 on 2026-02-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_alter_lead_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'permissions': [('view_leads', 'View Leads Page(Menu)'), ('can_update_lead', 'can update lead'), ('can_delete_lead', 'can delete lead'), ('can_book_lead', 'can book lead'), ('view_contacts', 'View Contacts'), ('change_contact', 'Change_Contact'), ('delete_contact', 'Delete_Contact')]},
        ),
    ]
